- hosts: localhost
  connection: local

  tasks:
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: ansibleLab
        location: eastasia

    - name: Create virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: ansibleLab
        name: ansible-vnet
        address_prefixes: "172.16.0.0/16"

    - name: Create Netwrok Security group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: ansibleLab
        name: ansible-vnet-nsg

    - name: Create subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: ansibleLab
        virtual_network_name: ansible-vnet
        name: workload-subnet
        address_prefix_cidr: "172.16.1.0/24"
        security_group: ansible-vnet-nsg

    - name: Create Public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: ansibleLab
        name: ansible-controller-pip
        allocation_method: static



